export enum BookCategoryTitles {
	ARCHITECTURE = 'Architecture',
	ART_FASHION = 'Art & Fashion',
	BIOGRAPHY = 'Biography',
	BUSINESS = 'Business',
	CRAFTS_HOBBIES = 'Crafts & Hobbies',
	DRAMA = 'Drama',
	FICTION = 'Fiction',
	FOOD_DRINK = 'Food & Drink',
	HEALTH_WELLBEING = 'Health & Wellbeing',
	HISTORY_POLITICS = 'History & Politics',
	HUMOR = 'Humor',
	POETRY = 'Poetry',
	PSYCHOLOGY = 'Psychology',
	SCIENCE = 'Science',
	TECHNOLOGY = 'Technology',
	TRAVEL_MAPS = 'Travel & Maps',
}

export const bookCategories = [
	{ id: 1, title: 'Architecture', path: '/architecture' },
	{ id: 2, title: 'Art & Fashion', path: '/art-fashion' },
	{ id: 3, title: 'Biography', path: '/biography' },
	{ id: 4, title: 'Business', path: '/business' },
	{ id: 5, title: 'Crafts & Hobbies', path: '/crafts-hobbies' },
	{ id: 6, title: 'Drama', path: '/drama' },
	{ id: 7, title: 'Fiction', path: '/fiction' },
	{ id: 8, title: 'Food & Drink', path: '/food-drink' },
	{ id: 9, title: 'Health & Wellbeing', path: '/health-wellbeing' },
	{ id: 10, title: 'History & Politics', path: '/history-politics' },
	{ id: 11, title: 'Humor', path: '/humor' },
	{ id: 12, title: 'Poetry', path: '/poetry' },
	{ id: 13, title: 'Psychology', path: '/psychology' },
	{ id: 14, title: 'Science', path: '/science' },
	{ id: 15, title: 'Technology', path: '/technology' },
	{ id: 16, title: 'Travel & Maps', path: '/travel-maps' },
]
